- DESCRIPTION
- inst/pkgdown/templates/content-syllabus.html
I should not try to write HTML when I'm tired, it turns out. Because schedule was templated as a page-header, the CSS demanded that it have a more prominent z-axis than the rest of the content and was covering it up. Thanks to @fmichonneau for pointing out the cause: https://github.com/zkamvar/sandpaper-docs/issues/1
> make schedule section a section

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/content-syllabus.html
This will update to address https://github.com/carpentries/sandpaper/issues/260 by creating sections for the setup and syllabus sections for the index page.
This will pair with https://github.com/carpentries/sandpaper/pull/262
> Modify index template for setup navigation

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/footer.html
From https://github.com/carpentries/actions/releases/tag/v0.8, it is possible for lesson authors to specify their own versions of sandpaper and varnish to build thier lessons. This PR adds the `sandpaper_cfg` and `varnish_cfg` variables to the footer links so that the correct links can be added in (once sandpaper accounts for these).
> Add alternative workbench links

- NEWS.md
- inst/pkgdown/templates/footer.html
This updates the CoC link to point to `CODE_OF_CONDUCT.md`, which allows folks to include their own codes of conduct.
> update code of conduct link

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/navbar.html
Because we are not yet at the point where we are using the term "Chapters", we want to make sure the infrastructure is consistent, so we are renaming this header back to "Episodes"
> CHAPTERS -> EPISODES

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/navbar.html
This adds the correct resources in the dropdown by default so that users on mobile will have the same access.
This will fix https://github.com/carpentries/varnish/issues/49
See https://github.com/carpentries/sandpaper/issues/306 for details of issue
> hard-code generated resources in mobile nav

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/footer.html
- inst/pkgdown/templates/header.html
This adds more information for lessons in the beta phase
- more icons for different stages of the beta
- wavy overline for feedback
- learn more link goes to workbench beta page
This also gives lessons in alpha a more visible icon by setting yellow as the background
> update workbench beta message:

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/header.html
For lessons that use `workbench-beta: true`, the feedback URL has changed from <https://github.com/carpentries/workbench/discussions/> to <https://carpentries.typeform.com/to/KRBl4IZM>, so that we can get more specific feedback.
> add survey url

- inst/pkgdown/templates/content-chapter.html
- inst/pkgdown/templates/footer.html
This will modify "Edit on GitHub"/"Edit this page" urls so that they point to
`https://carpentries.github.io/workbench/contributor/<phase>.html?<url-to-edit`
This will address the question posed in https://github.com/carpentries/workbench/discussions/30
Here is an example of what clicking on "Improve this page" will look like from
[the fourth episode of R for ecologists](https://preview.carpentries.org/R-ecology-lesson/03-dplyr.html).
https://carpentries.github.io/workbench/contributor/pre-beta.html?id=https://github.com/fishtree-attempt/R-ecology-lesson/edit/main/episodes/03-dplyr.Rmd
> modify beta urls

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/footer.html
In my haste with version 0.2.7, I accidentally duplicated the edit on
github URLs, which caused the footer to be malformed. I had additionally
added an extra closing p tag where it was not needed.
This will fix #65
> fix footer

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/footer.html
We got a warning that our yearly price will increase for analytics.
Considering that I still do not have a good grasp on how the analytics works
means that I need to spend time shaving that yak. Until then, I am disabling 
matomo analytics for varnish.
> temporarily turn of matomo analytics

- inst/pkgdown/templates/content-chapter.html
- inst/pkgdown/templates/footer.html
the "edit on github" was moving people to the beta stage landing page, which was inaccurate for the preview version.
> fix beta url in footer

- source/stylesheets/schedule.scss
Set the `margin-bottom` to 25 px instead of 225 px. I don't have a specific reason for this number, but it is a lot smaller. Fixes #81.
> Make space below schedule smaller

- DESCRIPTION
- NEWS.md
- inst/pkgdown/templates/head.html
This removes the use of `$` delimiters for MathJax since pandoc will allow those.
You can confirm this works by doing the following:
1. clone `carpentries/sandpaper-docs`
2. add these lines to `index.md`:
```markdown
I have \$2 USD and \$5 CAD
This is math $1\frac{a}{b}$
```
3. install this version of varnish: `devtools::install("carpentries/varnish#90")`
4. preview the lesson with sandpaper
This will fix #88
> allow inline text with dollarsigns to be not mathed

- DESCRIPTION
- inst/pkgdown/templates/head.html
- inst/pkgdown/templates/header.html
There is currently a bug whereby `title` (from `config.yaml`), if containing `&`, will be double encoded to converting them to `&amp;amp;` in 4 locations of the templates. This presumably applies to other HTML encoded characters too.
See: https://github.com/r-lib/pkgdown/pull/298, where they addressed the same issue, albeit with a different fix (which caused `NULL` to be rendered when I attempted with the carpentries template).
The same fix already appears present on this and the following lines: https://github.com/carpentries/varnish/blob/8b930523e56f4003b381353d6f945228664584a4/inst/pkgdown/templates/header.html#L42
I'm not particularly familiar with `pkgdown`, [`mustache`](https://mustache.github.io/mustache.5.html) (where I found this alt-fix) or R, so it's possible there's a better …
> Bugfix: Avoid double html escaping of lesson title.

- NEWS.md
- source/stylesheets/overview.scss
Making this change inside chrome's dev tools fixes it, at the cost of limiting the font size when the side bar is collapsed (with the sidebar collapsed, on a 1440p monitor the font size would previously peak at 27.12px and not wrap)
It caps the font size to 25px, as the issue occurs at ~25.29px.
Before (27.12px)
After (25px)
Might be possible to instead dynamically apply the cap when the sidebar is expanded. But I'm far from a front-end web developer.
I'm not sure I understand why the font even scales with screen width, above 1350px screen width (with sidebar collapsed) or 1229px (with sidebar expanded), the box it's contained within has a static size. Furthermore, when screen width drops below 1200px, the sidebar is hidden so the box expands to follow screen width but the font size …
> Bugfix: .card-title text would wrap at high screen widths.

- NEWS.md
- source/stylesheets/header.scss
Before
After
The rule sits within a media breakpoint so is only active between window widths 768-1200px, otherwise that particular element is `display: none`. Likewise, the search box appears to have a static size/position whilst visible (although the green magnifying glass does alot of walking about at widths >1200px). So I don't think this will introduce any new issues.
Closes #84
> Bugfix: Lesson title would collide with search box at certain widths.

- inst/pkgdown/templates/header.html
The goal of this PR (in combination with SANDPAPER PR LINK) is to:
The screenshot below shows the replacement of the search box icon with a button pointing towards the lesson's all in one page: 
Note to self and @froggleston - if we end up merging this, please squash and merge, there's a lot of commits where I was experimenting.
Fixes https://github.com/carpentries/workbench/issues/8
> Direct to all in one page for search

- inst/pkgdown/templates/header.html
Fixes https://github.com/carpentries/varnish/issues/135
Clicking the "Search the All in One page" from Instructor view brings up the Instructor AIO (with Instructor notes shown):
While clicking "Search the All in One page" from the Learner view brings up the Learner version of the page (with no Instructor notes):
Thanks to @tobyhodges for noticing this and to @froggleston for help with the moustach syntax!
> Make "Search All in One" aware of learner/instructor distinction

- inst/pkgdown/templates/footer.html
This PR aims to fix #37, alongside https://github.com/carpentries/sandpaper/pull/586.
> Add support for configurable analytics

- inst/pkgdown/templates/head.html
Fix https://github.com/carpentries/varnish/issues/33.
Also fix point 1 in https://github.com/carpentries/sandpaper/issues/241 thanks to https://github.com/carpentries/sandpaper/pull/585.
Tested locally on https://github.com/swcarpentry/r-novice-inflammation and https://github.com/epiverse-trace/research-compendium.
> Use favicon for specific carpentries

- source/stylesheets/styles.css.scss
- source/stylesheets/syntax-highlighting.scss
Follow up from #151 
Without the first commit, `squash-sass.sh` complains because the `mono_font` variable has not yet been created when `syntax-highlighthing.scss` is turned into css.
> Load Sass variables early and use mono_font variable

- source/stylesheets/styles.css.scss
Fixes an issue where h3 and h4 elements would scale to larger sizes than h1 or h2 on larger monitors
> Limit h3 and h4 sizes on wider monitors

- inst/pkgdown/templates/header.html
I noticed the alpha/beta link from the header was pointing to the old docs.
New page doesn't appear to have anchors that can be linked, but it's short so I don't think that's an issue.
*I completed instructor training in February, I think this PR can be used as one of my checkout things🤷‍♂️, though I'd have made it regardless.*
> Update life-cycle badge link to new docs
